import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
// const robotoSlab = Roboto_Slab({ subsets: ['latin'], weight:["100","300","400",'500','700','900'] })

export const metadata = {
  title: 'Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
